"""
Compress data/*.csv (+ the model outputs from tools/train_model.py) into
web/data.js — the payload the browser build reads. No server, no database:
everything the four tools need ships inside the page.

Compression choices (see docs/architecture.md):
  - dividends reduced to which months of 2024 a company paid in
  - indices_cleaned run-length encoded: a bare year means "same indicator
    values as the row before it" (the table is gap-filled, so ~65% of rows
    are exact repeats)
  - money columns (capital, total_liabilities, net_income) stored in millions

Usage:
    python tools/build_payload.py
"""
import json
import re

import pandas as pd

DATA = "data"


def base_symbol(s):
    return re.sub(r"\.SR$", "", str(s))


def main():
    companies = pd.read_csv(f"{DATA}/companies.csv")
    companies["symbol"] = companies["symbol"].apply(base_symbol)
    companies["company_name"] = companies["company_name"].str.strip()
    companies["sector"] = companies["sector"].str.strip()  # fixes a stray-leading-space "Insurance" dup

    dividend_ttm = pd.read_csv(f"{DATA}/dividend_ttm.csv")
    dividend_ttm["symbol"] = dividend_ttm["symbol"].apply(base_symbol)
    ttm_map = dict(zip(dividend_ttm["symbol"], dividend_ttm["dividend_ttm"]))

    dividends = pd.read_csv(f"{DATA}/dividends.csv", parse_dates=["distribution_date"])
    dividends["symbol"] = dividends["symbol"].apply(base_symbol)
    div2024 = dividends[dividends["distribution_date"].dt.year == 2024]
    months_2024 = {
        sym: sorted(set(int(m) for m in g["distribution_date"].dt.month))
        for sym, g in div2024.groupby("symbol")
    }

    indices_cleaned = pd.read_csv(f"{DATA}/indices_cleaned.csv")
    indices_cleaned["symbol"] = indices_cleaned["symbol"].apply(base_symbol)

    # last close price per symbol - a small derived file (see
    # tools/compute_last_close.py), so build_payload.py never needs the full
    # 9MB historical_prices.csv to run.
    lc_df = pd.read_csv(f"{DATA}/last_close.csv")
    lc_df["symbol"] = lc_df["symbol"].apply(base_symbol)
    last_close = dict(zip(lc_df["symbol"], lc_df["last_close"]))
    print(f"[INFO] last close loaded for {len(last_close)} symbols from data/last_close.csv")

    predicted = pd.read_csv(f"{DATA}/predicted_prices_rf.csv")
    predicted["symbol"] = predicted["symbol"].apply(base_symbol)
    last_actual = pd.read_csv(f"{DATA}/last_actual_prices.csv")
    last_actual["symbol"] = last_actual["symbol"].apply(base_symbol)
    with open("model_metrics.json") as f:
        metrics = json.load(f)

    companies_rows = [[r["symbol"], r["company_name"], r["sector"]] for _, r in companies.iterrows()]

    IND_COLS = ["capital", "total_liabilities", "net_income", "roe", "roa", "pe", "eps", "bvps", "de"]

    def round_row(row):
        out = []
        for c in IND_COLS:
            v = row[c]
            if pd.isna(v):
                out.append(None)
            elif c in ("capital", "total_liabilities", "net_income"):
                out.append(round(float(v) / 1_000_000, 3))
            else:
                out.append(round(float(v), 5))
        return out

    indices_payload = {}
    for sym, g in indices_cleaned.sort_values(["symbol", "year"]).groupby("symbol"):
        entries, prev_vals = [], None
        for _, row in g.iterrows():
            vals = round_row(row)
            year = int(row["year"])
            entries.append(year if vals == prev_vals else [year] + vals)
            prev_vals = vals
        indices_payload[sym] = entries

    pred_by_symbol = {sym: g.set_index("year")["predicted_price_rf"].to_dict() for sym, g in predicted.groupby("symbol")}
    growth_payload = {}
    for _, r in last_actual.iterrows():
        sym = r["symbol"]
        p = pred_by_symbol.get(sym)
        if not p or 2025 not in p or 2026 not in p or 2027 not in p:
            continue
        growth_payload[sym] = [int(r["last_year"]), round(float(r["last_price"]), 4),
                                round(float(p[2025]), 4), round(float(p[2026]), 4), round(float(p[2027]), 4)]

    last_close_payload = {sym: round(float(v), 2) for sym, v in last_close.items()}

    payload = {
        "companies": companies_rows,
        "dividendTtm": {k: round(float(v), 4) for k, v in ttm_map.items()},
        "months2024": months_2024,
        "lastClose": last_close_payload,
        "indices": indices_payload,
        "growth": growth_payload,
        "modelMetrics": metrics,
        "meta": {
            "companiesCount": len(companies_rows),
            "payersCount": len(ttm_map),
            "generatedFrom": "Namaa_backup.dump (real IS499 database, extracted with pgdumplib)",
        },
    }

    js = "// Generated by tools/build_payload.py from the real Namaa database dump.\n"
    js += "window.NAMAA_DATA = " + json.dumps(payload, separators=(",", ":"), ensure_ascii=False) + ";\n"

    import os
    os.makedirs("web", exist_ok=True)
    with open("web/data.js", "w", encoding="utf-8") as f:
        f.write(js)

    size_kb = os.path.getsize("web/data.js") / 1024
    print(f"[INFO] web/data.js written: {size_kb:.1f} KB "
          f"(companies={len(companies_rows)} payers={len(ttm_map)} "
          f"indices_symbols={len(indices_payload)} growth={len(growth_payload)})")


if __name__ == "__main__":
    main()
